(global-set-key (kbd "C-l") 'goto-line)
(global-set-key (kbd "C-/") 'comment-or-uncomment-region)
;;(global-set-key (kbd "M-o") 'helm-find-files)
;;(global-set-key (kbd "C-c") 'kill-ring-save)
;;(global-set-key (kbd "C-v") 'yank)
(global-set-key (kbd "C-.") 'revert-buffer)
(global-set-key (kbd "C-k") 'kill-whole-line)
(global-set-key (kbd "C-b") 'counsel-switch-buffer)
(global-set-key (kbd "C-s") 'swiper-isearch)
(global-set-key (kbd "C-S-f") 'lsp-format-buffer)
;;(global-set-key (kbd "M-x") 'helm-smex)
;;(global-set-key (kbd "C-S-r") 'helm-locate)
(global-set-key (kbd "C-o") 'ivy-imenu-anywhere)
(global-set-key (kbd "M-k") 'kill-this-buffer)
(global-set-key (kbd "RET") 'newline)
(global-set-key (kbd "C-z") 'undo)
(global-set-key (kbd "C-S-z") 'redo)
(global-set-key (kbd "s-o") 'projectile-find-file-dwim)
(global-set-key (kbd "s-p") 'counsel-find-file)
;;buffer跳转
(global-set-key (kbd "M-<left>") 'back-button-global-backward)
(global-set-key (kbd "M-<right>") 'back-button-global-forward)
(global-set-key (kbd "M-h") 'hs-toggle-hiding)

(add-hook 'term-mode-hook '(lambda()
                             (define-key term-raw-map (kbd "C-y") 'term-paste)
                             (define-key term-raw-map (kbd "M-x") 'counsel-M-x)
                             (define-key term-raw-map (kbd "C-b") 'counsel-switch-buffer)
                             (define-key term-raw-map (kbd "s-p") 'counsel-find-file)
                             (define-key term-raw-map (kbd "C-k")  (define-key term-raw-map (kbd "C-k")
                                                                     (lambda ()
                                                                       (interactive)
                                                                       (term-send-raw-string "\C-k")
                                                                       (kill-line))))))
(add-hook 'vterm-mode-hook '(lambda()
                              (define-key vterm-mode-map (kbd "C-y") 'term-paste)
                              (define-key vterm-mode-map (kbd "M-x") 'counsel-M-x)
                              (define-key vterm-mode-map (kbd "C-b") 'counsel-switch-buffer)
                              (define-key term-raw-map (kbd "s-p") 'counsel-find-file)
                              (define-key vterm-mode-map (kbd "C-k") (define-key vterm-mode-map (kbd "C-k")
                                                                       (interactive)
                                                                       (term-send-raw-string "\C-k")
                                                                       (kill-line)))))
(electric-indent-mode -1)
(setq-default indent-tabs-mode nil)
(global-set-key (kbd "<C-up>") 'shrink-window)
(global-set-key (kbd "<C-down>") 'enlarge-window)
(global-set-key (kbd "<C-left>") 'shrink-window-horizontally)
(global-set-key (kbd "<C-right>") 'enlarge-window-horizontally)
(provide 'init-keybinds)
