;;; -*- lexical-binding: t; -*-
(global-set-key (kbd "C-l") 'consult-goto-line)
(global-set-key (kbd "C-/") 'comment-or-uncomment-region)
;;(global-set-key (kbd "M-o") 'helm-find-files)
;;(global-set-key (kbd "C-c") 'kill-ring-save)
;;(global-set-key (kbd "C-v") 'yank)
(global-set-key (kbd "M-u") 'upcase-region)
(global-set-key (kbd "M-l") 'downcase-region)
(global-set-key (kbd "C-.") 'revert-buffer)
(global-set-key (kbd "C-k") 'kill-whole-line)
(global-set-key (kbd "C-b") 'switch-to-buffer);;counsel-switch-buffer
(global-set-key (kbd "C-s") 'consult-line)
(global-set-key (kbd "C-S-f") 'lsp-format-buffer)
(global-set-key (kbd "M-w") 'er/mark-word)
;;(global-set-key (kbd "C-S-r") 'helm-locate)
(global-set-key (kbd "C-o") 'consult-imenu);;ivy-imenu-anywhere
(global-set-key (kbd "M-k") 'centaur-tabs--kill-this-buffer-dont-ask)
(global-set-key (kbd "RET") 'newline)
(global-set-key (kbd "C-z") 'undo)
(global-set-key (kbd "C-S-z") 'redo)
(global-set-key (kbd "s-o") 'consult-find)
(global-set-key (kbd "s-p") 'ido-find-file)
(global-set-key (kbd "M-x") 'counsel-M-x)
;;buffer跳转
;;(global-set-key (kbd "M-<left>") 'back-button-global-backward)
;;(global-set-key (kbd "M-<right>") 'back-button-global-forward)
(global-set-key (kbd "M-h") 'hs-toggle-hiding)
(global-set-key (kbd "s-u") 'ssh-deploy-upload-handler-forced)
;;(global-set-key (kbd "s-.") 'ggtags-find-definition)

(add-hook 'term-mode-hook '(lambda()
                             (define-key term-raw-map (kbd "C-y") 'term-paste)
                             (define-key term-raw-map (kbd "M-x") 'counsel-M-x)
                             (define-key term-raw-map (kbd "C-b") 'consult-buffer)
                             (define-key term-raw-map (kbd "s-p") 'counsel-find-file)
                             (define-key term-raw-map (kbd "C-k")  (define-key term-raw-map (kbd "C-k")
                                                                     (lambda ()
                                                                       (interactive)
                                                                       (term-send-raw-string "\C-k")
                                                                       (kill-line))))))
(add-hook 'vterm-mode-hook '(lambda()
                              (define-key vterm-mode-map (kbd "C-y") 'term-paste)
                              (define-key vterm-mode-map (kbd "M-x") 'counsel-M-x)
                              (define-key vterm-mode-map (kbd "C-b") 'counsel-switch-buffer)
                              (define-key term-raw-map (kbd "s-p") 'counsel-find-file)
                              (define-key vterm-mode-map (kbd "C-k") (define-key vterm-mode-map (kbd "C-k")
                                                                   (interactive)
                                                                   (term-send-raw-string "\C-k")
                                                                   (kill-line)))))
;;(setq-default indent-tabs-mode nil)
;;(setq-default electric-indent-mode nil)
;;(setq-default indent-line-function 'insert-tab)
;;(global-set-key (kbd "M-<up>") 'shrink-window)
;;(global-set-key (kbd "M-<down>") 'enlarge-window)
;;(global-set-key (kbd "M-<left>") 'shrink-window-horizontally)
;;(global-set-key (kbd "M-<right>") 'enlarge-window-horizontally)

;;(global-set-key (kbd "s-j") 'centaur-tabs-backward)
;;(global-set-key (kbd "s-k") 'centaur-tabs-forward)

(provide 'init-keybinds)
