#!/bin/sh

JDTLS_REPOSITORY=/Users/chenlong/.emacs.d/javalibs/jdt
JDTLS_LAUNCHER=$(ls $JDTLS_REPOSITORY/plugins/org.eclipse.equinox.launcher_*.jar)
JDTLS_CONFIG=config_mac
JDTLS_WORKSPACE=~/.emacs.d/workspace

java -Declipse.application=org.eclipse.jdt.ls.core.id1 \
     -Dosgi.bundles.defaultStartLevel=4 \
     -Declipse.product=org.eclipse.jdt.ls.core.product \
     -Dlog.level=ERROR \
     -noverify \
     -jar $JDTLS_LAUNCHER \
     -configuration $JDTLS_REPOSITORY/$JDTLS_CONFIG \
     -data $JDTLS_WORKSPACE \
     --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED \
     -XX:+AggressiveOpts \
     -XX:PermSize=512m -XX:MaxPermSize=512m \
     -Xms512m -Xmx2048m \
     -Xmn512m \
     -Xss2m \
     -XX:+UseG1GC \
     -XX:+UseLargePages

