name: CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version: [25.1, 25.3, 26.3, 27.2, 28.1]
        experimental: [false]
        include:
          - emacs-version: snapshot
            experimental: true

    steps:
      - name: setenv
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Test
        run: |
          export HOME="$HOME/work/.emacs.d"; \
          mkdir -p $HOME/.emacs.d/elpa/gnupg && gpg --homedir $HOME/.emacs.d/elpa/gnupg --receive-keys 066DAFCB81E42C40; \
          emacs --version; \
          emacs -q --batch \
          --eval "(message \"Testing...\")" \
          --eval "(when (and (require 'org nil t) (string= (org-version) \"\"))
                     (advice-add 'org-version :override (lambda (&rest _) \"9.3\")))" \
          --eval "(let ((early-init-file (locate-user-emacs-file \"early-init.el\"))
                        (user-init-file (locate-user-emacs-file \"init.el\")))
                    (and (>= emacs-major-version 27) (load early-init-file))
                    (load user-init-file))" \
          --eval "(message \"Testing...done\")"
